name: Android CI Build (APK)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
    paths:
      - 'android-app/**'
      - '.github/workflows/android-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK (Command-line tools)
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses and install required packages
        shell: bash
        run: |
          set -e
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

      - name: Configure Android SDK path for Gradle
        shell: bash
        run: |
          echo "sdk.dir=${ANDROID_HOME}" > android-app/local.properties
          cat android-app/local.properties

      - name: Build with Gradle (assembleDebug)
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '8.7'
          build-root-directory: android-app
          arguments: assembleDebug --stacktrace --no-daemon --warning-mode all
          cache-disabled: true

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: android-app/app/build/outputs/apk/debug/app-debug.apk
          if-no-files-found: error
